export function generateRandomName() {
    const nameList = [
        "Anuj",
        "Ashi",
        "Nany",
        "Dev",
        "Kirti",
        "Nobita",
        "Shinchan",
        "Sakshi",
        "Pooja",
        "Fenu",
        "Honey",
        "Jasmine",
        "Geeta",
        "Ram",
        "Sita",
        "Laksh",
        "Daksh",
        "Darshit",
        "Neha",
        "Nehal",
        "Moksh",
        "Raju",
        "Oshin",
        "Katrina",
        "Ashwariya",
        "Anushka",
        "Virat",
        "Alia",
        "Garv",
        "Bhavi",
        "Aditi",
        "Aditya",
        "Boski",
        "Roski",
        "Sonu",
        "Khushi",
        "Khushbu",
        "Sanjay",
        "Sandesh",
        "Lalit",
        "Kanika",
        "Raj",
        "Rani",
        "Rehman",
        "Reshma",
        "Rashmika",
        "Arun",
        "Mahak",
        "Gungun",
        "Laila",
        "Nishchay",
        "Prerna",
        "Asher",
        "Abhi",
        "Abhir",
        "Abhira",
        "Ruhi",
        "Arunima",
        "Insiya",
        "Ranveer",
        "Ranbir",
        "Kaveri",
        "Kriti",
        "Shreya",
        "Shruti",
        "Shraddha",
        "Kanishka",
        "Kanishk",
        "Urvashi",
        "Rohit",
        "Riddhi",
        "Atharva",
        "Somi",
        "Chatali",
        "Manas",
        "Manasi",
        "Tanish",
        "Sparsh",
        "Tanisha",
        "Manish",
        "Manisha",
        "Bhavna",
        "Ranbir",
        "Sushant",
        "Ankita",
        "Vicky",
        "Sapna",
        "Sangeeta",
        "Saroj",
        "Usha",
        "Arpita",
        "Faagun",
        "Dhani",
        "Surbhi",
        "Ankur",
        "Prayan",
        "Avani",
        "Kushal",
        "Cherry",
        "Anmol",
        "Ojasvi",
        "Aishee",
        "Raman",
        "Ishita",
        "Shivam",
        "Navam",
        "Tahir",
        "Gautam",
        "Faris",
        "Muskan",
        "Siddhi",
        "Anvesha",
        "Aarushi",
        "Rishi",
        "Bharat",
        "Bharti",
        "Joy",
        "Joyful",
        "Crimson",
        "Destiny",
        "Deceit",
        "Lies",
        "Lie",
        "Honest",
        "Destined",
        "Bloxxer",
        "Hawk",
        "Eagle",
        "Hawker",
        "Walker",
        "Zombie",
        "Sarge",
        "Capt",
        "Captain",
        "Punch",
        "One",
        "Two",
        "Uno",
        "Slice",
        "Slash",
        "Melt",
        "Melted",
        "Melting",
        "Fell",
        "Wolf",
        "Hound",
        "Legacy",
        "Sharp",
        "Dead",
        "Mew",
        "Chuckle",
        "Bubba",
        "Bubble",
        "Sandwich",
        "Smasher",
        "Extreme",
        "Multi",
        "Universe",
        "Ultimate",
        "Death",
        "Ready",
        "Monkey",
        "Elevator",
        "Wrench",
        "Grease",
        "Head",
        "Theme",
        "Grand",
        "Cool",
        "Kid",
        "Boy",
        "Girl",
        "Vortex",
        "Paradox",
    ];
    return nameList[Math.floor(Math.random() * nameList.length)];
}

export function generateRandomText(numParagraphs, numSentencesPerParagraph) {
    const words = [
        "lorem",
        "ipsum",
        "dolor",
        "sit",
        "amet",
        "consectetur",
        "adipiscing",
        "elit",
        "sed",
        "do",
        "eiusmod",
        "tempor",
        "incididunt",
        "ut",
        "labore",
        "et",
        "dolore",
        "magna",
        "aliqua",
    ];
    const paragraphs = [];

    for (let p = 0; p < numParagraphs; p++) {
        const sentences = [];

        for (let i = 0; i < numSentencesPerParagraph; i++) {
            const numWords = Math.floor(Math.random() * 10) + 5;
            const sentenceWords = [];

            for (let j = 0; j < numWords; j++) {
                const randomIndex = Math.floor(Math.random() * words.length);
                sentenceWords.push(words[randomIndex]);
            }

            const sentence = sentenceWords.join(" ") + ".";
            sentences.push(
                sentence.charAt(0).toUpperCase() + sentence.slice(1)
            );
        }

        paragraphs.push(sentences.join(" "));
    }

    return paragraphs.join("\n\n");
}